// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ9nK52ceCsWQMZ-mpGoKn-QVJiZRmw9o',
    appId: '1:753540561905:web:f3b372445df97ce392a250',
    messagingSenderId: '753540561905',
    projectId: 'amid-login',
    authDomain: 'amid-login.firebaseapp.com',
    storageBucket: 'amid-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq8xJbqGFgPtaM6W--MyU_OqPadzhirF0',
    appId: '1:753540561905:android:89ae189a9f715cf092a250',
    messagingSenderId: '753540561905',
    projectId: 'amid-login',
    storageBucket: 'amid-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ypPtefe4-aMnlcAUbXfGWzQzvuTO1RQ',
    appId: '1:753540561905:ios:c3369c9a2cb6671092a250',
    messagingSenderId: '753540561905',
    projectId: 'amid-login',
    storageBucket: 'amid-login.appspot.com',
    iosClientId: '753540561905-beub58dv3tt1bsko9im230rse425gcdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.amid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ypPtefe4-aMnlcAUbXfGWzQzvuTO1RQ',
    appId: '1:753540561905:ios:c3369c9a2cb6671092a250',
    messagingSenderId: '753540561905',
    projectId: 'amid-login',
    storageBucket: 'amid-login.appspot.com',
    iosClientId: '753540561905-beub58dv3tt1bsko9im230rse425gcdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.amid',
  );
}
